### ISSUE TITLE
Can't generate policy. It is throwing error 

### ISSUE THREAD

**Issue by DeboDevelop** [commutatus/cm-admin#176]
Can't generate policy. It is throwing error 

```
$ rails g cm_admin:policy milestone
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
warning: parser/current is loading parser/ruby27, which recognizes2.7.6-compliant syntax, but you are running 2.7.1.
Please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
Traceback (most recent call last):
	19: from bin/rails:4:in `<main>'
	18: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	17: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	16: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/railties-6.1.6/lib/rails/commands.rb:18:in `<main>'
	15: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/railties-6.1.6/lib/rails/command.rb:48:in `invoke'
	14: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/railties-6.1.6/lib/rails/command/base.rb:69:in `perform'
	13: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	12: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	11: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	10: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/railties-6.1.6/lib/rails/commands/generate/generate_command.rb:26:in `perform'
	 9: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/railties-6.1.6/lib/rails/generators.rb:275:in `invoke'
	 8: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	 7: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/thor-1.2.1/lib/thor/group.rb:232:in `dispatch'
	 6: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/thor-1.2.1/lib/thor/invocation.rb:134:in `invoke_all'
	 5: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/thor-1.2.1/lib/thor/invocation.rb:134:in `map'
	 4: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/thor-1.2.1/lib/thor/invocation.rb:134:in `each'
	 3: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/thor-1.2.1/lib/thor/invocation.rb:134:in `block in invoke_all'
	 2: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	 1: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
/home/tukai/.rvm/gems/ruby-2.7.1/gems/cm-admin-0.6.8/lib/generators/cm_admin/policy_generator.rb:10:in `copy_policy_files': cm_admin is not defined inside milestone model (RuntimeError)
```

**Comment by AdityaTiwari2102** [comment]
@DeboDevelop - Based on the error logged `cm_admin is not defined inside milestone model (RuntimeError)` you need to define the `cm_admin` block in the model.

**Comment by AdityaTiwari2102** [comment]
Similar to #161. Hence, closing this.
