### ISSUE TITLE
Cm-admin is failing for model with active storage

### ISSUE THREAD

**Issue by DeboDevelop** [commutatus/cm-admin#177]
Cm-admin is failing for model with active storage attached with them.
The error throw is

```
=> Booting Puma
=> Rails 6.1.6 application starting in development 
=> Run `bin/rails server --help` for more startup options
Exiting
Traceback (most recent call last):
	75: from bin/rails:4:in `<main>'
	74: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	73: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	72: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/railties-6.1.6/lib/rails/commands.rb:18:in `<main>'
	71: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/railties-6.1.6/lib/rails/command.rb:48:in `invoke'
	70: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/railties-6.1.6/lib/rails/command/base.rb:69:in `perform'
	69: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	68: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	67: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	66: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/railties-6.1.6/lib/rails/commands/server/server_command.rb:135:in `perform'
	65: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/railties-6.1.6/lib/rails/commands/server/server_command.rb:135:in `tap'
	64: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/railties-6.1.6/lib/rails/commands/server/server_command.rb:144:in `block in perform'
	63: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/railties-6.1.6/lib/rails/commands/server/server_command.rb:37:in `start'
	62: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/railties-6.1.6/lib/rails/commands/server/server_command.rb:77:in `log_to_stdout'
	61: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
	60: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
	59: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
	58: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
	57: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
	56: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
	55: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
	54: from config.ru:5:in `block in <main>'
	53: from config.ru:5:in `require_relative'
	52: from /home/tukai/Commutatus/climber-api/config/environment.rb:7:in `<main>'
	51: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/railties-6.1.6/lib/rails/application.rb:391:in `initialize!'
	50: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/railties-6.1.6/lib/rails/initializable.rb:60:in `run_initializers'
	49: from /home/tukai/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
	48: from /home/tukai/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
	47: from /home/tukai/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
	46: from /home/tukai/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:347:in `call'
	45: from /home/tukai/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:347:in `each'
	44: from /home/tukai/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
	43: from /home/tukai/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:415:in `each_strongly_connected_component_from'
	42: from /home/tukai/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:415:in `call'
	41: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/railties-6.1.6/lib/rails/initializable.rb:50:in `tsort_each_child'
	40: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/railties-6.1.6/lib/rails/initializable.rb:50:in `each'
	39: from /home/tukai/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	38: from /home/tukai/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
	37: from /home/tukai/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	36: from /home/tukai/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	35: from /home/tukai/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
	34: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/railties-6.1.6/lib/rails/initializable.rb:61:in `block in run_initializers'
	33: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/railties-6.1.6/lib/rails/initializable.rb:32:in `run'
	32: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/railties-6.1.6/lib/rails/initializable.rb:32:in `instance_exec'
	31: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/railties-6.1.6/lib/rails/engine.rb:633:in `block in <class:Engine>'
	30: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/railties-6.1.6/lib/rails/engine.rb:633:in `each'
	29: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/railties-6.1.6/lib/rails/engine.rb:634:in `block (2 levels) in <class:Engine>'
	28: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/railties-6.1.6/lib/rails/engine.rb:680:in `load_config_initializer'
	27: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/activesupport-6.1.6/lib/active_support/notifications.rb:205:in `instrument'
	26: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/railties-6.1.6/lib/rails/engine.rb:681:in `block in load_config_initializer'
	25: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:326:in `load'
	24: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:299:in `load_dependency'
	23: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:326:in `block in load'
	22: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
	21: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
	20: from /home/tukai/Commutatus/climber-api/config/initializers/zcm_admin.rb:1:in `<main>'
	19: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/cm-admin-0.6.8/lib/cm_admin.rb:28:in `configure'
	18: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/cm-admin-0.6.8/lib/cm_admin.rb:28:in `instance_eval'
	17: from /home/tukai/Commutatus/climber-api/config/initializers/zcm_admin.rb:4:in `block in <main>'
	16: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:213:in `const_missing'
	15: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:558:in `load_missing_constant'
	14: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:402:in `require_or_load'
	13: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:39:in `load_interlock'
	12: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/activesupport-6.1.6/lib/active_support/dependencies/interlock.rb:13:in `loading'
	11: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/activesupport-6.1.6/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
	10: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/activesupport-6.1.6/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
	 9: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:39:in `block in load_interlock'
	 8: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:419:in `block in require_or_load'
	 7: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:522:in `load_file'
	 6: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:715:in `new_constants_in'
	 5: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:523:in `block in load_file'
	 4: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
	 3: from /home/tukai/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
	 2: from /home/tukai/Commutatus/climber-api/app/models/milestone.rb:3:in `<main>'
	 1: from /home/tukai/Commutatus/climber-api/app/models/milestone.rb:20:in `<class:Milestone>'
/home/tukai/.rvm/gems/ruby-2.7.1/gems/activerecord-6.1.6/lib/active_record/dynamic_matchers.rb:22:in `method_missing': undefined method `has_one_attached' for Milestone (call 'Milestone.connection' to establish a connection):Class (NoMethodError)
```

Adding these 3 lines in the model is fixing the issue
```
  include ActiveStorage::Reflection::ActiveRecordExtensions
  ActiveRecord::Reflection.singleton_class.prepend(ActiveStorage::Reflection::ReflectionExtension)
  include ActiveStorage::Attached::Model
```

**Comment by AdityaTiwari2102** [comment]
@DeboDevelop - This is a known issue. If you move to [7:41 in the video](https://app.weet.co/play/be169698/cm-admin-installation-steps) it is mentioned with the solution. We will include it in the documentation.
